name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js with a compatible version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10' # Adjust based on Quasar v0.14 compatibility

      # Install dependencies
      - name: Install dependencies
        working-directory: ./public
        run: npm install

      # Build the project for production
      - name: Build project
        working-directory: ./public
        run: quasar build

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
